# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: echo Hello, world!
    - name: Run tests
      run: | 
        xcodebuild clean test -project DDD-Community/DDD-8-IOS-2-healthRoutine/healthRoutine.xcodeproj -scheme healthRoutine -destination "platform=iOS Simulator,name=iPhone 13"
